### Listar os moradores
GET https://localhost:5001/api/morador/listar

### Cadastrar um morador
POST https://localhost:5001/api/morador/cadastrar
Content-Type: application/json

{

    "nome" : "Eduardo Kuritza",
    "cpf" : "07661385938",
    "apartamento": "1",
    "Email": "elkuritza@gmail.com",
    "bloco": "1",
    "modelo_veiculo": "corsa",
    "cor": "preto",
    "placa": "AAA-123"

}

### Buscar um morador pelo CPF
GET https://localhost:5001/api/morador/buscar/08697637928

### Deletar um morador pelo Id
DELETE https://localhost:5001/api/morador/deletar/1

### Alterar um morador
PATCH  https://localhost:5001/api/morador/alterar
Content-Type: application/json

{
    "moradorId" : 1,
    "nome" : "Eduardo Kuritza Modificado",
    "cpf" : "07661385938",
    "apartamento": "3",
    "Email": "elkuritza@gmail.com",
    "bloco": "3",
    "modelo_veiculo": "Ferrari",
    "cor": "vermelha",
    "placa": "CCC-123"
}